// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcalllcsuguepwkmngid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjYWxsbGNzdWd1ZXB3a21uZ2lkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzU4OTIsImV4cCI6MjA2MzY1MTg5Mn0.sa09lF_j2oIt8dnrwsvHX-szsFYsoIHFYEx8i_JwaVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);